<?php


namespace app\index\controller;


use app\BaseController;
use app\model\FriendshipLink;
use think\facade\Env;
use think\facade\View;

class Base extends BaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uid = cookie('xwx_user_id');
        $vip_expire_time = cookie('vip_expire_time');
        if (!empty($vip_expire_time)){
            if($vip_expire_time - time() <= 0){ //计算出会员是否过期
                cookie('xwx_vip_expire_time', null);
            }
        }
        $this->prefix = Env::get('database.prefix');
        $this->redis_prefix = Env::get('cache.prefix');
        $this->end_point = config('seo.book_end_point');
        $tpl_root = './template/'.config('site.tpl').'/pc/';
        $controller = strtolower($this->request->controller());
        $action = strtolower($this->request->action());
        $this->tpl = $tpl_root.$controller.'/'.$action.'.html';

        $links = cache('friendshipLink');
        if ($links == false){
            $links = FriendshipLink::select();
            cache('friendshipLink',$links,null,'redis');
        }
        View::assign([
            'links' => $links,
            'url' => config('site.schema').config('site.domain'),
            'site_name' => config('site.site_name'),
            'mobile_url' => config('site.schema').config('site.mobile_domain'),
            'book_ctrl' => BOOKCTRL,
            'chapter_ctrl' => CHAPTERCTRL,
            'booklist_act' => BOOKLISTACT,
            'search_ctrl' => SEARCHCTRL,
            'rank_ctrl' => RANKCTRL,
            'update_act' => UPDATEACT,
            'author_ctrl' => AUTHORCTRL,
            'end_point' => config('seo.book_end_point'),
            'xwx_user_id' => cookie('xwx_user_id'),
            'xwx_user' => cookie('xwx_user'),
            'xwx_nick_name' => cookie('xwx_nick_name'),
            'xwx_user_mobile'=> cookie('xwx_user_mobile'),
            'xwx_vip_expire_time' => cookie('xwx_vip_expire_time'),
        ]);
    }
}